"use client";

import { useState, useEffect, useCallback, useMemo } from "react";
import { createClient } from "@/lib/supabase/client";
import { useErrorLogs } from "@/hooks/useErrorLogs";
import type { DailyErrorLog } from "@/types";
import { PageHeader } from "@/components/ui/PageHeader";
import { CopyButton } from "@/components/ui/CopyButton";
import { ImagePasteZone } from "@/components/ui/ImagePasteZone";
import { generateErrorReportText } from "@/lib/report-generators/error";
import { getTodayDisplay } from "@/lib/utils";

export function ErrorLogsPage() {
  const { logs, loading, error, createLog } = useErrorLogs();
  const [errorText, setErrorText] = useState("");
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  const supabase = useMemo(() => createClient(), []);

  // 1. REALTIME SYNC: Dengarkan ketikan user lain
  useEffect(() => {
    const channel = supabase.channel('snippet-room');
    channel.on('broadcast', { event: 'snippet-update' }, (payload) => {
      setErrorText(payload.payload.text);
    }).subscribe();

    return () => { supabase.removeChannel(channel); };
  }, [supabase]);

  // 2. BROADCAST: Kirim ketikan kita ke user lain
  const handleTextChange = (val: string) => {
    setErrorText(val);
    supabase.channel('snippet-room').send({
      type: 'broadcast',
      event: 'snippet-update',
      payload: { text: val },
    });
  };

  const handleImageChange = useCallback((file: File | null, preview: string | null) => {
    setImageFile(file);
    setImagePreview(preview);
  }, []);

  const handleSave = useCallback(async () => {
    if (!errorText.trim()) return;

    setSaving(true);
    setSaveError(null);

    const firstLine = errorText.split('\n')[0].trim();
    const autoGeneratedTitle = firstLine.length > 40 ? firstLine.substring(0, 40) + "..." : firstLine;

    try {
      await createLog({
        errorTitle: autoGeneratedTitle || "Error Snippet",
        errorTextLog: errorText.trim(),
        screenshotFile: imageFile,
      });
      // Bersihkan form setelah save
      handleTextChange("");
      setImageFile(null);
      setImagePreview(null);
    } catch (e) {
      setSaveError(e instanceof Error ? e.message : "Failed to save");
    } finally {
      setSaving(false);
    }
  }, [errorText, imageFile, createLog]);

  return (
    <>
      <PageHeader
        title="Error / Incident Log"
        description="Document operational errors with screenshots"
        date={getTodayDisplay()}
        actions={
          <CopyButton
            label="Copy Error Report"
            onCopy={async () => generateErrorReportText(logs)}
          />
        }
      />

      <div className="mx-auto max-w-6xl px-4 py-4 sm:px-6">
        {error && (
          <p className="mb-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700 dark:bg-red-500/10 dark:text-red-400">
            {error}
          </p>
        )}

        <div className="mb-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
          <h2 className="mb-4 text-sm font-semibold text-slate-900 dark:text-slate-100">
            Live Shared Snippet
          </h2>

          <div className="space-y-4">
            <div className="overflow-hidden rounded-xl border border-slate-300 bg-slate-50 shadow-inner dark:border-slate-700 dark:bg-[#0d1117]">
              <div className="bg-slate-200/50 px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:bg-white/5 dark:text-slate-400">
                Live Log
              </div>
              <textarea
                value={errorText}
                onChange={(e) => handleTextChange(e.target.value)}
                placeholder="Type or paste logs here to share in real-time..."
                rows={8}
                spellCheck={false}
                className="w-full resize-y bg-transparent p-4 font-mono text-sm leading-relaxed text-slate-800 focus:outline-none dark:text-slate-300"
              />
            </div>

            <ImagePasteZone preview={imagePreview} onImageChange={handleImageChange} />

            <button
              type="button"
              onClick={handleSave}
              disabled={saving || !errorText.trim()}
              className="w-full rounded-lg bg-indigo-600 px-4 py-3 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 transition-colors sm:w-auto"
            >
              {saving ? "Saving..." : "Save Snippet Permanently"}
            </button>
          </div>
        </div>

        {/* ... (ErrorLogCard sama dengan sebelumnya) ... */}
      </div>
    </>
  );
}